version: 2.1

commands:
  pull_submodules:
    steps:
      - run:
          name: Pull submodules
          command: git submodule init && git submodule update
  install_dependencies:
    steps:
      - restore_cache:
          name: Restore modules cache
          keys:
            - node_modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save modules cache
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

jobs:
  build:
    docker:
      - image: circleci/node:12.19.0
    steps:
      - checkout
      - setup_remote_docker
      - pull_submodules
      - install_dependencies
      - run: yarn typecheck
      - run: yarn build
  lint:
    docker:
      - image: circleci/node:12.19.0
    steps:
      - run: yarn lint
  test:
    docker:
      - image: circleci/node:12.19.0
    steps:
      - run: yarn test
  upgrade:
    docker:
      - image: circleci/node:12.19.0
    steps:
      - run: yarn test:upgrade

workflows:
  version: 2
  test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - upgrade:
          requires:
            - build
