name: CI
on: [push]
jobs:
  node:
    name: Set up environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.9.0
      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - run: yarn install --frozen-lockfile
        if: steps.cache-node.outputs.cache-hit != 'true'

  build:
    name: Build contracts
    needs: node
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.9.0
      - name: Get the environment
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - run: yarn build
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build

  check:
    name: Lint and typecheck
    needs: [node, build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.9.0
      - name: Get the environment
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - name: Download build
        uses: actions/download-artifact@v2
      - run: yarn typecheck
      - run: yarn lint

  tests-group1:
    name: Governance, proxy, registry, scripts
    needs: [node, build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.9.0
      - name: Get the environment
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - name: Download build
        uses: actions/download-artifact@v2
      - run: yarn test:governance
      - run: yarn test:proxy
      - run: yarn test:registry
      - run: yarn test:scripts

  tests-group2:
    name: True currencies and True gold
    needs: [node, build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.9.0
      - name: Get the environment
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - name: Download build
        uses: actions/download-artifact@v2
      - run: yarn test:true-currencies
      - run: yarn test:true-gold

  tests-group3:
    name: TrueFi loans and others
    needs: [node, build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.9.0
      - name: Get the environment
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - name: Download build
        uses: actions/download-artifact@v2
      - run: yarn test:truefi:loans
      - run: yarn test:truefi:others

  tests-group4:
    name: TrueFi services
    needs: [node, build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.9.0
      - name: Get the environment
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - name: Download build
        uses: actions/download-artifact@v2
      - run: yarn test:truefi:service

  tests-group5:
    name: Trust token and Tru Farm
    needs: [node, build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.9.0
      - name: Get the environment
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - name: Download build
        uses: actions/download-artifact@v2
      - run: yarn test:trusttoken

  tests-upgrade:
    name: Storage corruption check
    needs: [node, build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.9.0
      - name: Get the environment
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - name: Download build
        uses: actions/download-artifact@v2
      - run: yarn test:upgrade
