name: CI
on: [push]
jobs:
  node:
    name: Set up environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.9.0
      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - run: yarn install --frozen-lockfile
        if: steps.cache-node.outputs.cache-hit != 'true'
      - name: Upload environment
        uses: actions/upload-artifact@v2
        with:
          name: node
          path: ./.github/workflows/artifacts

  build:
    name: Build contracts
    needs: node
    runs-on: ubuntu-latest

    steps:
      - name: Get environment
        uses: actions/download-artifact@v2
      - run: yarn build
